package render

import (
	"fmt"
	"strings"

	"github.com/whitagotchi/whitagotchi/shared"
)

// Creature renders a creature plus its stats as multi-line ASCII (one frame).
func Creature(c *shared.Creature) string {
	return CreatureFrame(c, 0)
}

// CreatureFrame renders a specific animation frame (0 or 1).
func CreatureFrame(c *shared.Creature, frame int) string {
	var b strings.Builder
	b.WriteString(Frame(c.Species, c.Stage, frame))
	b.WriteString("\n")
	fmt.Fprintf(&b, "%s the %s (%s, %s)\n", c.OwnerName, c.Species, c.Rarity, c.Stage)
	if c.Stage == shared.StageAdult && c.AdultForm != "" {
		fmt.Fprintf(&b, "adult form: %s\n", c.AdultForm)
	}
	fmt.Fprintf(&b, "quirk: %s\n", c.Quirk)
	b.WriteString("\n")
	fmt.Fprintf(&b, "  hunger      %s\n", Bar(c.Stats.Hunger))
	fmt.Fprintf(&b, "  happiness   %s\n", Bar(c.Stats.Happiness))
	fmt.Fprintf(&b, "  cleanliness %s\n", Bar(c.Stats.Cleanliness))
	return b.String()
}

// Bar renders a 0-100 stat as a 20-wide bar.
func Bar(v int) string {
	filled := v / 5
	if filled < 0 {
		filled = 0
	}
	if filled > 20 {
		filled = 20
	}
	return fmt.Sprintf("[%s%s] %d", strings.Repeat("#", filled), strings.Repeat(".", 20-filled), v)
}

// Frame returns the ASCII art for a species+stage at the given animation frame.
// Frame 0 is the resting pose; frame 1 is a blink/idle variant generated by
// substituting eye glyphs.
func Frame(s shared.Species, st shared.Stage, frame int) string {
	base := art(s, st)
	if frame%2 == 0 {
		return base
	}
	return blink(base)
}

// blink swaps common eye glyphs for a closed/half-closed variant.
// It's a cheap way to get animation without authoring two full sprites per stage.
var blinkPairs = []struct{ open, closed string }{
	{"o.o", "-.-"},
	{"o o", "- -"},
	{"o_o", "-_-"},
	{"o  o", "-  -"},
	{"o   o", "-   -"},
	{"^.^", "-.-"},
	{". .", "- -"},
	{"o ^ o", "- ^ -"},
	{"@_@", "x_x"},
	{"@   @", "x   x"},
	{"@     @", "x     x"},
	{"(o.o)", "(-.-)"},
}

func blink(s string) string {
	out := s
	for _, p := range blinkPairs {
		out = strings.ReplaceAll(out, p.open, p.closed)
	}
	return out
}

func art(s shared.Species, st shared.Stage) string {
	if st == shared.StageEgg {
		return eggArt
	}
	if frames, ok := speciesArt[s]; ok {
		if a, ok := frames[st]; ok {
			return a
		}
	}
	return fallback
}
